services:
  web:
    image: buffalo_theater_shows:latest
    restart: unless-stopped
    volumes:
      - ./src:/src
    ports:
      - "5666:5666"
    depends_on:
      - ollama
      - redis

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_volume:/root/.ollama
    restart: unless-stopped

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data:
  ollama_volume: