services:
  web:
    image: buffalo_theater_shows:latest
    restart: unless-stopped
    security_opt:
      - "seccomp=./seccomp_profile.json"
    volumes:
      - ./src:/src
    ports:
      - "8501:8501"
#    depends_on:
#      - ollama

#  ollama:
#    image: ollama/ollama
#    ports:
#      - "11434:11434"
#    volumes:
#      - ollama_volume:/root/.ollama
#    restart: unless-stopped

volumes:
  ollama_volume: