services:
  web:
    image: buffalo_theater_shows:latest
    restart: unless-stopped
    command: streamlit run main.py --server.enableCORS=false --server.enableWebsocketCompression=false
    security_opt:
      - "seccomp=./seccomp_profile.json"
    volumes:
      - ./src:/src
    ports:
      - "8501:8501"
    env_file:
      - .env